frr version 10.5.0_git
frr defaults traditional
hostname r6
log stdout informational
log file /var/log/frr.log
service integrated-vtysh-config
!
route-map ORIGIN_IGP permit 10
 set origin igp
exit
!
vrf mgmt
exit-vrf
!
interface lo
 ip address 172.16.0.6/32
 ipv6 address fc00:0:6::1/128
exit
!
router bgp 4200000006
 bgp router-id 172.16.0.6
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 timers bgp 10 30
 neighbor FABRIC peer-group
 neighbor FABRIC remote-as external
 neighbor FABRIC timers connect 5
 neighbor FABRIC capability extended-nexthop
 neighbor eth1 interface peer-group FABRIC
 neighbor eth2 interface peer-group FABRIC
 !
 address-family ipv4 unicast
  redistribute connected route-map ORIGIN_IGP
  neighbor FABRIC activate
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected route-map ORIGIN_IGP
  neighbor FABRIC activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  advertise-all-vni
  vni 20
   rd 4200000000:20
   route-target import 4200000000:20
   route-target export 4200000000:20
  exit-vni
  advertise-svi-ip
 exit-address-family
exit
!
segment-routing
 traffic-eng
 exit
exit
!
